//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ActionConfig&gt;
        ///
        ///	&lt;Entity name=&quot;baseEntity&quot;&gt;
        ///		&lt;OnStar&gt;ShowActions&lt;/OnStar&gt;
        ///		&lt;OnRecord&gt;RefreshMetadata&lt;/OnRecord&gt;
        ///	&lt;/Entity&gt;
        ///
        ///	&lt;Entity name=&quot;Item&quot;&gt;
        ///		&lt;OnEnter&gt;ShowActions&lt;/OnEnter&gt;
        ///		&lt;OnPlay&gt;Play&lt;/OnPlay&gt;
        ///		&lt;MenuItems&gt;
        ///			&lt;Item&gt;Play&lt;/Item&gt;
        ///			&lt;Item&gt;RefreshMetadata&lt;/Item&gt;
        ///		&lt;/MenuItems&gt;
        ///	&lt;/Entity&gt;
        ///
        ///	&lt;Entity name=&quot;Container&quot;&gt;
        ///		&lt;OnEnter&gt;Open&lt;/OnEnter&gt;
        ///		&lt;OnPlay&gt;ShowActions&lt;/OnPlay&gt;
        ///		&lt;MenuItems&gt;
        ///			&lt;Item&gt;Play&lt;/Item&gt;
        ///			&lt;Item&gt;Shuffle&lt;/Item&gt;
        ///			&lt;Item&gt;Open&lt;/Item&gt;
        ///			&lt;Item&gt;RefreshMetadata&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionConfig {
            get {
                return ResourceManager.GetString("ActionConfig", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bit_16_bits {
            get {
                object obj = ResourceManager.GetObject("bit_16 bits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bit_24_bits {
            get {
                object obj = ResourceManager.GetObject("bit_24 bits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bit_8_bits {
            get {
                object obj = ResourceManager.GetObject("bit_8 bits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Settings&gt;&lt;/Settings&gt;.
        /// </summary>
        internal static string BlankSettings {
            get {
                return ResourceManager.GetString("BlankSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] buttonAction {
            get {
                object obj = ResourceManager.GetObject("buttonAction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] buttonBasic {
            get {
                object obj = ResourceManager.GetObject("buttonBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] buttonIcon {
            get {
                object obj = ResourceManager.GetObject("buttonIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] buttonImage {
            get {
                object obj = ResourceManager.GetObject("buttonImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap channels_1 {
            get {
                object obj = ResourceManager.GetObject("channels_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap channels_2 {
            get {
                object obj = ResourceManager.GetObject("channels_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkSelected {
            get {
                object obj = ResourceManager.GetObject("checkSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkUnselected {
            get {
                object obj = ResourceManager.GetObject("checkUnselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_aac {
            get {
                object obj = ResourceManager.GetObject("codec_aac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_ac_3 {
            get {
                object obj = ResourceManager.GetObject("codec_ac-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_asf {
            get {
                object obj = ResourceManager.GetObject("codec_asf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_avc {
            get {
                object obj = ResourceManager.GetObject("codec_avc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_dts {
            get {
                object obj = ResourceManager.GetObject("codec_dts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_flac {
            get {
                object obj = ResourceManager.GetObject("codec_flac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpeg_audio {
            get {
                object obj = ResourceManager.GetObject("codec_mpeg audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpeg_video {
            get {
                object obj = ResourceManager.GetObject("codec_mpeg video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_pcm {
            get {
                object obj = ResourceManager.GetObject("codec_pcm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_theora {
            get {
                object obj = ResourceManager.GetObject("codec_theora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vc_1 {
            get {
                object obj = ResourceManager.GetObject("codec_vc-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vorbis {
            get {
                object obj = ResourceManager.GetObject("codec_vorbis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wma {
            get {
                object obj = ResourceManager.GetObject("codec_wma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap container_avi {
            get {
                object obj = ResourceManager.GetObject("container_avi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap container_bdav {
            get {
                object obj = ResourceManager.GetObject("container_bdav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap container_dvd {
            get {
                object obj = ResourceManager.GetObject("container_dvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap container_matroska {
            get {
                object obj = ResourceManager.GetObject("container_matroska", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ctrlActionPopUp {
            get {
                object obj = ResourceManager.GetObject("ctrlActionPopUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlCheckbox {
            get {
                object obj = ResourceManager.GetObject("ctrlCheckbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlFooter {
            get {
                object obj = ResourceManager.GetObject("ctrlFooter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlHeader {
            get {
                object obj = ResourceManager.GetObject("ctrlHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlPlayListAction {
            get {
                object obj = ResourceManager.GetObject("ctrlPlayListAction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlScrollingText {
            get {
                object obj = ResourceManager.GetObject("ctrlScrollingText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlTextBox {
            get {
                object obj = ResourceManager.GetObject("ctrlTextBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlThumb {
            get {
                object obj = ResourceManager.GetObject("ctrlThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlViewMenu {
            get {
                object obj = ResourceManager.GetObject("ctrlViewMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlViewPopUp {
            get {
                object obj = ResourceManager.GetObject("ctrlViewPopUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap defaultBackground {
            get {
                object obj = ResourceManager.GetObject("defaultBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DisplaySettings {
            get {
                object obj = ResourceManager.GetObject("DisplaySettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconAction {
            get {
                object obj = ResourceManager.GetObject("IconAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconBorder {
            get {
                object obj = ResourceManager.GetObject("IconBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconClose {
            get {
                object obj = ResourceManager.GetObject("IconClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconConfig {
            get {
                object obj = ResourceManager.GetObject("IconConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconDeleteCache {
            get {
                object obj = ResourceManager.GetObject("IconDeleteCache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconDown {
            get {
                object obj = ResourceManager.GetObject("IconDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconFastForward {
            get {
                object obj = ResourceManager.GetObject("IconFastForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconFavorite {
            get {
                object obj = ResourceManager.GetObject("IconFavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconGroup {
            get {
                object obj = ResourceManager.GetObject("IconGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconHalfStar {
            get {
                object obj = ResourceManager.GetObject("IconHalfStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconHome {
            get {
                object obj = ResourceManager.GetObject("IconHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconMinus {
            get {
                object obj = ResourceManager.GetObject("IconMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconNew {
            get {
                object obj = ResourceManager.GetObject("IconNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconOpen {
            get {
                object obj = ResourceManager.GetObject("IconOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPause {
            get {
                object obj = ResourceManager.GetObject("IconPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlay {
            get {
                object obj = ResourceManager.GetObject("IconPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlaylist {
            get {
                object obj = ResourceManager.GetObject("IconPlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlus {
            get {
                object obj = ResourceManager.GetObject("IconPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconQueue {
            get {
                object obj = ResourceManager.GetObject("IconQueue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRefresh {
            get {
                object obj = ResourceManager.GetObject("IconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRepeat {
            get {
                object obj = ResourceManager.GetObject("IconRepeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconResume {
            get {
                object obj = ResourceManager.GetObject("IconResume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRewind {
            get {
                object obj = ResourceManager.GetObject("IconRewind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSearch {
            get {
                object obj = ResourceManager.GetObject("IconSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconShuffle {
            get {
                object obj = ResourceManager.GetObject("IconShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSkipBack {
            get {
                object obj = ResourceManager.GetObject("IconSkipBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSkipForward {
            get {
                object obj = ResourceManager.GetObject("IconSkipForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSort {
            get {
                object obj = ResourceManager.GetObject("IconSort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconStar {
            get {
                object obj = ResourceManager.GetObject("IconStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconStop {
            get {
                object obj = ResourceManager.GetObject("IconStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconUnknown {
            get {
                object obj = ResourceManager.GetObject("IconUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconUp {
            get {
                object obj = ResourceManager.GetObject("IconUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconView {
            get {
                object obj = ResourceManager.GetObject("IconView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageAlbum {
            get {
                object obj = ResourceManager.GetObject("imageAlbum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageArtist {
            get {
                object obj = ResourceManager.GetObject("imageArtist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageFolder {
            get {
                object obj = ResourceManager.GetObject("imageFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageGenre {
            get {
                object obj = ResourceManager.GetObject("imageGenre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imagePlaylist {
            get {
                object obj = ResourceManager.GetObject("imagePlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageSpinner {
            get {
                object obj = ResourceManager.GetObject("imageSpinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageTrack {
            get {
                object obj = ResourceManager.GetObject("imageTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageVideo {
            get {
                object obj = ResourceManager.GetObject("imageVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicBrowser2 {
            get {
                object obj = ResourceManager.GetObject("MusicBrowser2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] MusicSettings {
            get {
                object obj = ResourceManager.GetObject("MusicSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavPanel {
            get {
                object obj = ResourceManager.GetObject("NavPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nullImage {
            get {
                object obj = ResourceManager.GetObject("nullImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] pageFolder {
            get {
                object obj = ResourceManager.GetObject("pageFolder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pageFooBar2000 {
            get {
                object obj = ResourceManager.GetObject("pageFooBar2000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pageSearch {
            get {
                object obj = ResourceManager.GetObject("pageSearch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pageSettings {
            get {
                object obj = ResourceManager.GetObject("pageSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radioSelected {
            get {
                object obj = ResourceManager.GetObject("radioSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radioUnselected {
            get {
                object obj = ResourceManager.GetObject("radioUnselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rate_44_1_KHz {
            get {
                object obj = ResourceManager.GetObject("rate_44.1 KHz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rate_96_KHz {
            get {
                object obj = ResourceManager.GetObject("rate_96 KHz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selectedMenu {
            get {
                object obj = ResourceManager.GetObject("selectedMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subs {
            get {
                object obj = ResourceManager.GetObject("Subs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SystemSettings {
            get {
                object obj = ResourceManager.GetObject("SystemSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap underline {
            get {
                object obj = ResourceManager.GetObject("underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] viewList {
            get {
                object obj = ResourceManager.GetObject("viewList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] viewStrip {
            get {
                object obj = ResourceManager.GetObject("viewStrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] viewThumb {
            get {
                object obj = ResourceManager.GetObject("viewThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
