//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap blackBorder {
            get {
                object obj = ResourceManager.GetObject("blackBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Settings&gt;&lt;/Settings&gt;.
        /// </summary>
        internal static string BlankSettings {
            get {
                return ResourceManager.GetString("BlankSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] buttonBasic {
            get {
                object obj = ResourceManager.GetObject("buttonBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] buttonIcon {
            get {
                object obj = ResourceManager.GetObject("buttonIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] buttonImage {
            get {
                object obj = ResourceManager.GetObject("buttonImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNoFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ctrlFooter {
            get {
                object obj = ResourceManager.GetObject("ctrlFooter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlGroupByPopUp {
            get {
                object obj = ResourceManager.GetObject("ctrlGroupByPopUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlHeader {
            get {
                object obj = ResourceManager.GetObject("ctrlHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlHomePopUp {
            get {
                object obj = ResourceManager.GetObject("ctrlHomePopUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlPlayListAction {
            get {
                object obj = ResourceManager.GetObject("ctrlPlayListAction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlPlayPopUp {
            get {
                object obj = ResourceManager.GetObject("ctrlPlayPopUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ctrlScrollingText {
            get {
                object obj = ResourceManager.GetObject("ctrlScrollingText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap defaultBackground {
            get {
                object obj = ResourceManager.GetObject("defaultBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconClose {
            get {
                object obj = ResourceManager.GetObject("IconClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconConfig {
            get {
                object obj = ResourceManager.GetObject("IconConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconGroup {
            get {
                object obj = ResourceManager.GetObject("IconGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconHome {
            get {
                object obj = ResourceManager.GetObject("IconHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPause {
            get {
                object obj = ResourceManager.GetObject("IconPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlay {
            get {
                object obj = ResourceManager.GetObject("IconPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlaylist {
            get {
                object obj = ResourceManager.GetObject("IconPlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconQueue {
            get {
                object obj = ResourceManager.GetObject("IconQueue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconResume {
            get {
                object obj = ResourceManager.GetObject("IconResume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconShuffle {
            get {
                object obj = ResourceManager.GetObject("IconShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageAlbum {
            get {
                object obj = ResourceManager.GetObject("imageAlbum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageArtist {
            get {
                object obj = ResourceManager.GetObject("imageArtist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageDisc {
            get {
                object obj = ResourceManager.GetObject("imageDisc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageFolder {
            get {
                object obj = ResourceManager.GetObject("imageFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageGenre {
            get {
                object obj = ResourceManager.GetObject("imageGenre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imagePlaylist {
            get {
                object obj = ResourceManager.GetObject("imagePlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageSpinner {
            get {
                object obj = ResourceManager.GetObject("imageSpinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageTrack {
            get {
                object obj = ResourceManager.GetObject("imageTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgButtonIcon {
            get {
                object obj = ResourceManager.GetObject("imgButtonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MusicBrowser2 {
            get {
                object obj = ResourceManager.GetObject("MusicBrowser2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nullImage {
            get {
                object obj = ResourceManager.GetObject("nullImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] pageFolder {
            get {
                object obj = ResourceManager.GetObject("pageFolder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pageSearch {
            get {
                object obj = ResourceManager.GetObject("pageSearch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radioSelected {
            get {
                object obj = ResourceManager.GetObject("radioSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radioUnselected {
            get {
                object obj = ResourceManager.GetObject("radioUnselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbAlbum {
            get {
                object obj = ResourceManager.GetObject("thumbAlbum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbArtist {
            get {
                object obj = ResourceManager.GetObject("thumbArtist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbFavorite {
            get {
                object obj = ResourceManager.GetObject("thumbFavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbFolder {
            get {
                object obj = ResourceManager.GetObject("thumbFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbGenre {
            get {
                object obj = ResourceManager.GetObject("thumbGenre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbPlaylist {
            get {
                object obj = ResourceManager.GetObject("thumbPlaylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbStar {
            get {
                object obj = ResourceManager.GetObject("thumbStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbTrack {
            get {
                object obj = ResourceManager.GetObject("thumbTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbVirtual {
            get {
                object obj = ResourceManager.GetObject("thumbVirtual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap underline {
            get {
                object obj = ResourceManager.GetObject("underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] viewList {
            get {
                object obj = ResourceManager.GetObject("viewList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] viewStrip {
            get {
                object obj = ResourceManager.GetObject("viewStrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] viewThumb {
            get {
                object obj = ResourceManager.GetObject("viewThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
