using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MusicBrowser.Metadata.LastFM
{
    class LoveTrackService
    {
        public struct LoveTractDTO
        {
        }

        public static void DoService(ref LoveTractDTO DTO)
        {
        }
    }
}

//track.love
//track (Required) : A track name (utf8 encoded)
//artist (Required) : An artist name (utf8 encoded)
//api_key (Required) : A Last.fm API key.
//api_sig (Required) : A Last.fm method signature. See authentication for more information.
//sk (Required) : A session key generated by authenticating a user via the authentication protocol.

//track.unlove
//track (Required) : A track name (utf8 encoded)
//artist (Required) : An artist name (utf8 encoded)
//api_key (Required) : A Last.fm API key.
//api_sig (Required) : A Last.fm method signature. See authentication for more information.
//sk (Required) : A session key generated by authenticating a user via the authentication protocol.